M48
; DRILL file {KiCad 8.0.1} date 2024-05-11T19:31:13-0300
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-05-11T19:31:13-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X6.6762Y-2.324
X6.8671Y-2.324
T2
X6.6644Y-2.2047
X6.8789Y-2.2047
M30
